/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conndb;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.*;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author root
 */
public class Inici extends javax.swing.JFrame {

    /*
     * Creates new form Inici
     */
    public Inici() {
        initComponents();
    }

    public Connection Cone() {
        Connection conn = null;

        String url = "jdbc:mysql://localhost:3306/univeylandia_test2";
        String user = "root";
        String password = "alumne";
        try {
            conn = DriverManager.getConnection(url, user, password);
            if (conn.isClosed()) {
                jLabel1.setText("No connectat");

            } else {
                jLabel1.setText("Connectat amb l'usuari " + user);
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        return conn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        consultetes = new javax.swing.JTextArea();
        executa = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        bianda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("No connectat");
        jLabel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel1FocusGained(evt);
            }
        });

        consultetes.setColumns(20);
        consultetes.setRows(5);
        jScrollPane1.setViewportView(consultetes);

        executa.setText("Select");
        executa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                executaFocusGained(evt);
            }
        });

        jButton2.setText("Tancar");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabla);

        bianda.setText("bianda");
        bianda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                biandaFocusGained(evt);
            }
        });
        bianda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                biandaMouseClicked(evt);
            }
        });
        bianda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biandaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(executa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bianda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)))
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(executa)
                    .addComponent(jButton2)
                    .addComponent(bianda))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel1FocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel1FocusGained

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        Connection conn = null;

        String url = "jdbc:mysql://localhost:3306/univeylandia_test2";
        String user = "root";
        String password = "alumne";
        try {
            conn = DriverManager.getConnection(url, user, password);
            if (conn.isClosed()) {
                jLabel1.setText("No connectat");

            } else {
                jLabel1.setText("Connectat amb l'usuari " + user);
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_formWindowActivated

    private void executaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_executaFocusGained
        // TODO add your handling code here:
        Connection conn = null;
        String url = "jdbc:mysql://localhost:3306/univeylandia_test2";
        String user = "root";
        String password = "alumne";
        try {
            
            conn = DriverManager.getConnection(url, user, password);
            
            String consulta = consultetes.getText();
            
            Statement stmt = conn.createStatement();
            
            ResultSet rs = stmt.executeQuery(consulta);
            
            //imprimir en taula
            DefaultTableModel modelo = new DefaultTableModel();
           
            tabla.setModel(modelo);
            
            ResultSetMetaData dades = rs.getMetaData();
            
            int numCol = dades.getColumnCount();
             
            //crear array 
            Object [] etiquetes = new Object[numCol];
            
            //recorre
            
            for(int i = 0; i < numCol; i++){
                etiquetes[i] = dades.getColumnLabel(i + 1);
                modelo.setColumnIdentifiers(etiquetes);
            }
            
            while(rs.next()){
                Object [] fila = new Object[numCol];
                
                for(int i = 0; i < numCol; i++){
                  fila[i] = rs.getObject(i + 1); 
                }
                modelo.addRow(fila);

            }
            
             
        } catch (Exception e) {

        }

    }//GEN-LAST:event_executaFocusGained

    private void biandaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_biandaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_biandaFocusGained

    private void biandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_biandaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_biandaMouseClicked

    private void biandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biandaActionPerformed
Connection conn = null;
        String url = "jdbc:mysql://localhost:3306/univeylandia_test2";
        String user = "root";
        String password = "alumne";
        try {
            
            conn = DriverManager.getConnection(url, user, password);
            
            String consulta = consultetes.getText();
            
            Statement stmt = conn.createStatement();
            
            stmt.executeUpdate(consulta);
            
            //System.out.println();
            //imprimir en taula
                   
        } catch (Exception e) {

        }

 
    }//GEN-LAST:event_biandaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inici().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bianda;
    private javax.swing.JTextArea consultetes;
    private javax.swing.JButton executa;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
